export { default as automaticallyLinkEntity } from "./automaticallyLinkEntity"
export { default as clearLinkedEntities } from "./clearLinkedEntities"
export { default as deleteEntity } from "./deleteEntity"
export { default as getEntityList } from "./getEntityList"
export { default as setEntity } from "./setEntity"
